In [ ]:
#Importar bibliotecas
import pandas as pd 
import numpy as np

In [2]:
#Ler o CSV
df = pd.read_csv('../data/nhl_draft_predraft_stats.csv', sep=';')
df.head()

,year,overall_pick,round,team,player,player_ep_id,position,nationality,amateur_league,seasons_pre_nhl,games_played,goals,assists,points,penalty_minutes,points_per_game,goals_per_game
0,2015,1,1,Edmonton Oilers,Connor McDavid,183442,F,CAN,OHL,3.0,166.0,97.0,188.0,285.0,104.0,1.72,0.58
1,2015,2,1,Buffalo Sabres,Jack Eichel,191959,F,USA,USDP,5.0,210.0,126.0,156.0,282.0,120.0,1.34,0.60
2,2015,3,1,Arizona Coyotes,Dylan Strome,228107,F,CAN,OHL,4.0,219.0,114.0,240.0,354.0,105.0,1.62,0.52
3,2015,4,1,Toronto Maple Leafs,Mitchell Marner,223194,F,CAN,OHL,3.0,184.0,96.0,205.0,301.0,145.0,1.64,0.52
4,2015,5,1,Carolina Hurricanes,Noah Hanifin,177710,D,USA,USHS-Prep,6.0,210.0,38.0,124.0,162.0,72.0,0.77,0.18

In [3]:
#Verificar existência de caracteres especiais
mask = df['player'].str.contains(r'[^\x00-\x7F]', na=False) | df['team'].str.contains(r'[^\x00-\x7F]', na=False)
df[mask][['player', 'team']]

               player                   team
25       Noah Juulsen     Montréal Canadiens
30         Jérémy Roy        San Jose Sharks
35      Gabriel Gagné        Ottawa Senators
47      Filip Chlapík        Ottawa Senators
51      Jérémy Lauzon          Boston Bruins
...               ...                    ...
2372  Gustav Sjöqvist   Vegas Golden Knights
2374   Andrew MacNiel     Montréal Canadiens
2383  Jérémy Loranger  Columbus Blue Jackets
2388  Felix Färhammar       New York Rangers
2394        Maxon Vig     Montréal Canadiens

[269 rows x 2 columns]

In [4]:
#Exibir os valores na coluna "position"
df['position'].value_counts()

position
F    1369
D     792
G     249
Name: count, dtype: int64

In [5]:
#Exibir o número de linhas e colunas do CSV
df.shape

(2410, 17)

In [ ]:
#Remover todas as linhas que correspondiam ao G (goleiro)
df = df[df['position'] != 'G']

In [7]:
#Exibir os valores na coluna "position" após a limpeza
df['position'].value_counts()

position
F    1369
D     792
Name: count, dtype: int64

In [8]:
#Exibir o número de linhas e colunas do CSV após a limpeza
df.shape

(2161, 17)

In [9]:
#Exibir quantas colunas apresentavam valores "vazios"
print(df.isnull().sum())

year               0
overall_pick       0
round              0
team               0
player             0
player_ep_id       0
position           0
nationality        0
amateur_league     4
seasons_pre_nhl    4
games_played       4
goals              4
assists            4
points             4
penalty_minutes    4
points_per_game    4
goals_per_game     4
dtype: int64

In [ ]:
#Remover as linhas que continham valores "vazios" nessas colunas
df = df.dropna(subset=['amateur_league', 'seasons_pre_nhl', 'games_played', 'goals', 'assists', 'points', 'penalty_minutes', 'points_per_game', 'goals_per_game'])

In [11]:
#Exibir quantas colunas apresentavam valores "vazios" após a limpeza
print(df.isnull().sum())

year               0
overall_pick       0
round              0
team               0
player             0
player_ep_id       0
position           0
nationality        0
amateur_league     0
seasons_pre_nhl    0
games_played       0
goals              0
assists            0
points             0
penalty_minutes    0
points_per_game    0
goals_per_game     0
dtype: int64

In [ ]:
#Salvar os dados limpos e um novo CSV
df.to_csv('../data/nhl_draft_clean.csv', index=False)